services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=GAR
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=123
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
     - ./db_data:/var/lib/postgresql/data/pgdata
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@admin.org
      PGADMIN_SETUP_EMAIL: test@admin.org
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_SETUP_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 10000:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
  postgres:
  pgadmin: