REGION: 54
XSD_ARCHIVE_PATH: D:\fias\gar_schemas.zip
FIAS_ARCHIVE_PATH: D:\fias\gar_xml (1).zip
PATH_TO_EXTRACT: D:\ext
FILES_TO_EXTRACT:
  ADDR_OBJ:
    XSD: ^AS_ADDR_OBJ_\d.+\.xsd$
    XML: ^AS_ADDR_OBJ_\d.+\.XML$
  ADDR_OBJ_TYPES:
    XSD: ^AS_ADDR_OBJ_TYPES_\d.+\.xsd$
    XML: ^AS_ADDR_OBJ_TYPES_\d.+\.XML$
  ADM_HIERARCHY:
    XSD: ^AS_ADM_HIERARCHY_\d.+\.xsd$
    XML: ^AS_ADM_HIERARCHY_\d.+\.XML$
  MUN_HIERARCHY:
    XSD: ^AS_MUN_HIERARCHY_\d.+\.xsd$
    XML: ^AS_MUN_HIERARCHY_\d.+\.XML$
  NORMATIVE_DOCS:
    XSD: ^AS_NORMATIVE_DOCS_\d.+\.xsd$
    XML: ^AS_NORMATIVE_DOCS_\d.+\.XML$
  NORMATIVE_DOCS_KINDS:
    XSD: ^AS_NORMATIVE_DOCS_KINDS_\d.+\.xsd$
    XML: ^AS_NORMATIVE_DOCS_KINDS_\d.+\.XML$
  NORMATIVE_DOCS_TYPES:
    XSD: ^AS_NORMATIVE_DOCS_TYPES_\d.+\.xsd$
    XML: ^AS_NORMATIVE_DOCS_TYPES_\d.+\.XML$
  OBJECT_LEVELS:
    XSD: ^AS_OBJECT_LEVELS_\d.+\.xsd$
    XML: ^AS_OBJECT_LEVELS_\d.+\.XML$
  OPERATION_TYPES:
    XSD: ^AS_OPERATION_TYPES_\d.+\.xsd$
    XML: ^AS_OPERATION_TYPES_\d.+\.XML$
  ADDR_OBJ_PARAMS:
    XSD: ^AS_PARAM_\d.+\.xsd$
    XML: ^AS_ADDR_OBJ_PARAMS_\d.+\.XML$
  PARAM_TYPES:
    XSD: ^AS_PARAM_TYPES_\d.+\.xsd$
    XML: ^AS_PARAM_TYPES_\d.+\.XML$
  REESTR_OBJECTS:
    XSD: ^AS_REESTR_OBJECTS_\d.+\.xsd$
    XML: ^AS_REESTR_OBJECTS_\d.+\.XML$